# Generated by Django 2.1.3 on 2018-11-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_rso',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superadmin',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('RSO', 'RSO'), ('Private', 'Private'), ('Public', 'Public')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_level',
            field=models.CharField(choices=[('Student', 'Student'), ('Admin', 'Admin'), ('Superadmin', 'Superadmin')], max_length=10, null=True),
        ),
    ]
