# Generated by Django 2.1.3 on 2018-11-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rso_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='time',
        ),
    ]
