# Generated by Django 2.1.3 on 2018-11-21 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='superadmin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='superadmin', to=settings.AUTH_USER_MODEL),
        ),
    ]
